site_name: JarPlace
pages:
    - 'Installation': 'index.md'
    - 'Sign Up': 'signup.md'
    - 'Log In': 'login.md'
    - 'Billing': 'billing.md'
    - 'Repositories': 'repositories.md'
    - 'Users': 'users.md'
